import SwiftUI

/// The iOS app entry point — the `@main` shell that renders `RootView`.
///
/// The Xcode project is generated by XcodeGen from `native/ios/project.yml` (no committed
/// `.xcodeproj`): it compiles all of `Sources/CovenantPathKit/**` + this `App/` source directly into
/// the `CovenantPath` target and links supabase-swift. (The root `Package.swift` exists only so
/// `swift test` can run the pure-logic tests as a library.) Because the sources are in this target's
/// own module, there is no `import CovenantPathKit`. See README.
@main
struct CovenantPathApp: App {
    var body: some Scene {
        WindowGroup {
            RootView()
        }
    }
}
